version: '3'
services:
  terraform:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.aws:/root/.aws
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]